config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "todays_workout#index"
  resources :routines, only: [:index]
  resources :workout_days, only: [:new]
  resources :lifts, except: [:destroy, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lift.rb
class Lift < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, allow_blank: false
  validates :one_rep_max, presence: true, allow_blank: false

  # todo: round to nearest 5 for 1rm

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  alias_attribute :days, :workout_days

  has_many :lifts
  has_many :workout_days
end

app/models/workout_day.rb
class WorkoutDay < ApplicationRecord
  alias_attribute :lifts, :workout_day_lifts

  belongs_to :user
  has_many :workout_day_lifts
end

app/models/workout_day_lift.rb
class WorkoutDayLift < ApplicationRecord
  belongs_to :workout_day

  # todo: weight as a computed property based on one_rep_max_pct
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lifts_controller.rb
class LiftsController < ApplicationController
  before_action :authenticate_user!

  def index
    @lifts = current_user.lifts.all.order(:name)
  end

  def edit
    id = params[:id]
    @lift = Lift.find(id)
  end

  def new
    @lift = Lift.new
  end

  def create
    @lift = current_user.lifts.create(lift_params)
    if @lift.valid?
      flash[:success] = "Created lift."
      redirect_to edit_lift_path(@lift)
    else
      flash[:error] = "Failed to create lift."
      redirect_to new_lift_path
    end
  end

  def update
    id = params[:id]
    @lift = Lift.find(id)
    if @lift.update(lift_params)
      flash[:success] = "#{@lift.name} updated."
    else
      flash[:error] = "#{@lift.name} failed to update."
    end
    redirect_to edit_lift_path(@lift)
  end

  private

  def lift_params
    params.require(:lift).permit(:name, :one_rep_max)
  end

end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :authenticate_user!

  def index
    @days = current_user.days
  end

end

app/controllers/todays_workout_controller.rb
class TodaysWorkoutController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/workout_days_controller.rb
class WorkoutDaysController < ApplicationController
  before_action :authenticate_user!

  def new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when "notice" then "alert alert-info"
      when "success" then "alert alert-success"
      when "error" then "alert alert-danger"
      when "alert" then "alert alert-warning"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkoutApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navigation' if user_signed_in? %>
    <%= render 'shared/flash' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/lifts/_form.html.erb
<% text = action.capitalize %>

<%= bootstrap_form_for @lift, url: {action: action} do |f| %>
  <%= f.text_field :name %>
  <%= f.number_field :one_rep_max %>
  <%= f.submit "#{text}" %>
<% end %>

app/views/lifts/edit.html.erb
<%= render partial: "form", locals: { lift: @lift, action: "update"} %>

app/views/lifts/index.html.erb
<ul class="list-group mb-4">
  <% @lifts.each do |lift| %>
    <%= link_to "#{lift.name}", edit_lift_path(lift.id), class: "list-group-item list-group-item-action" %>
  <% end %>
</ul>
<%= link_to 'New lift', new_lift_path, :class => "btn btn-primary"%>

app/views/lifts/new.html.erb
<%= render partial: "form", locals: { lift: @lift, action: "create"} %>

app/views/routines/index.html.erb
<ul class="list-group mb-4">
  <% @days.each do |day| %>
    <div class="list-group-item list-group-item-action"><%= day.name %></div>
  <% end %>
</ul> 

<%= link_to 'New workout day', new_workout_day_path, :class => "btn btn-primary"%>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light mb-4" id="navigation">
  <ul class="navbar-nav mr-auto">
    <%= render partial: "shared/navigation_link", locals: { path: root_path, name: "Workout"} %>
    <%= render partial: "shared/navigation_link", locals: { path: routines_path, name: "Routine"} %>
    <%= render partial: "shared/navigation_link", locals: { path: lifts_path, name: "Lifts"} %>
  </ul>
</header>

app/views/shared/_navigation_link.html.erb
<li class="nav-item <%= 'active' if current_page? path %>">
  <%= link_to "#{name}", path, class: "nav-link" %>
</li>

app/views/todays_workout/index.html.erb
<h1>TodaysWorkout#Index</h1>

<p><%= current_user.email %></p>

app/views/workout_days/new.html.erb
<h1>workout days</h1>